#!/usr/bin/env bash
# script that install nginx and configure it to redirect to another page when
# accessing the /redirect_me page.

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
echo -e "\nCompleted.\n"
